/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/shoe/shoe.gltf -o src/components/Shoe.jsx -k -K -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Shoe(props) {
  const { nodes, materials } = useGLTF("/shoe/shoe.gltf");
  return (
    <group {...props} dispose={null} scale={3}>
      <group name="Scene">
        <group
          name="Light"
          position={[4.076, 5.904, -1.005]}
          rotation={[1.89, 0.881, -2.045]}
        />
        <group
          name="Camera"
          position={[7.359, 4.958, 6.926]}
          rotation={[1.242, 0.33, -0.76]}
        />
        <group name="Shoe">
          <mesh
            name="shoe"
            geometry={nodes.shoe.geometry}
            material={materials.laces}
            material-color={props.customeColors.setStripes}
          />
          <mesh
            name="shoe_1"
            geometry={nodes.shoe_1.geometry}
            material={materials.mesh}
            material-color={props.customeColors.mesh}
          />
          <mesh
            name="shoe_2"
            geometry={nodes.shoe_2.geometry}
            material={materials.caps}
            material-color={props.customeColors.stripes}
          />
          <mesh
            name="shoe_3"
            geometry={nodes.shoe_3.geometry}
            material={materials.inner}
            material-color={props.customeColors.stripes}
          />
          <mesh
            name="shoe_4"
            geometry={nodes.shoe_4.geometry}
            material={materials.sole}
            material-color={props.customeColors.sole}
          />
          <mesh
            name="shoe_5"
            geometry={nodes.shoe_5.geometry}
            material={materials.stripes}
            material-color={props.customeColors.stripes}
          />
          <mesh
            name="shoe_6"
            geometry={nodes.shoe_6.geometry}
            material={materials.band}
            material-color={props.customeColors.stripes}
          />
          <mesh
            name="shoe_7"
            geometry={nodes.shoe_7.geometry}
            material={materials.patch}
            material-color={props.customeColors.stripes}
          />
        </group>
      </group>
    </group>
  );
}

export default Shoe;
useGLTF.preload("/shoe/shoe.gltf");
